Update contributing_guide.md
unionai-oss/unionml pull request #188
Opened 2022-10-08 16:12 UTC by Smartmind12

Closes #146 

Updated user guide to install `requirements-docs.txt`.

2022-10-08 19:53 UTC, cosmicBboy requested changes

2022-10-08 19:53 UTC, cosmicBboy commented on docs/source/contributing_guide.md
> +
you can replace original code snippet above with this one, since `requirements-docs.txt` also includes `requirements-dev.txt`

2022-10-09 02:24 UTC, Smartmind12 commented
@cosmicBboy I have updated as per your recommendation...kindly review and let me know if any other changes are required!

2022-10-13 05:31 UTC, eapolinario approved these changes

2022-10-13 05:31 UTC, merged